# Generated by Django 4.0.5 on 2022-11-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trasaction',
            old_name='Remarks',
            new_name='remarks',
        ),
    ]
