# Generated by Django 4.0.5 on 2022-11-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_remarks_trasaction_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('requested_by', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=20, null=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usertype')),
            ],
        ),
    ]
